# Generated by Django 4.1 on 2022-09-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0002_delete_history_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg_user',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=50)),
                ('tags', models.TextField()),
            ],
        ),
    ]
