# Generated by Django 4.1 on 2022-09-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_reg_user_name_alter_reg_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('hid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('ytlink', models.CharField(max_length=255)),
                ('dtlink', models.TextField()),
                ('tags', models.TextField()),
                ('user', models.IntegerField(null=True)),
            ],
        ),
    ]
